from typing import List, Optional, Tuple

def libcdio_version() -> str: ...

class Device:
    def __init__(self, device_path: Optional[str] = None) -> None: ...
    def last_session_lsn(self) -> int: ...
    def lead_out_lba(self) -> int: ...
    def track_listing(self) -> List[Tuple[int, int, int, str]]: ...
