from typing import List, Optional, Tuple

def last_session_lsn(device_path: Optional[str] = None) -> int: ...
def lead_out_lba(device_path: Optional[str] = None) -> int: ...
def libcdio_version() -> str: ...
def track_listing(device_path: Optional[str] = None) -> List[Tuple[int, int, int, str]]: ...
